import Foundation
import UniformTypeIdentifiers

// The Book type is generated by UniFFI in omnireader_core.swift
// UniFFI already generates: Equatable, Hashable conformances

// Add Identifiable conformance for SwiftUI
extension Book: Identifiable {
    // UniFFI Book already has `id: String` property, which satisfies Identifiable
}

extension Book {
    /// Preview book for SwiftUI previews
    static var preview: Book {
        Book(
            id: "preview-1",
            title: "Sample Book Title",
            author: "Sample Author",
            filePath: "/path/to/book.pdf",
            fileType: .pdf,
            coverData: nil,
            addedAt: Int64(Date().timeIntervalSince1970),
            lastReadAt: nil,
            totalPages: 100
        )
    }
}

/// EPUB file type identifier
extension UTType {
    static var epub: UTType {
        UTType(filenameExtension: "epub") ?? .data
    }
}
